volumes:
  postgresql_data:
    driver: local

services:
  postgres:
    restart: unless-stopped
    image: postgres:17.5
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=postgres
